# Generated by kibo from ge. Do not edit by hand.
# Templates: MIT (kibo-template-viper).
# Runtime: this file imports `dsviper`, distributed under
# LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
# requires a Commercial Licence from Digital Substrate.
# Generated from GE.dsmb by kibo-1.2.0.jar

"""
Python classes for concepts, clubs, enums and structs defined for ge.
"""

from .data import *
